PKGNAME := cparse
CPARSE_HEADERS := $(PKGINC_H) $(CUTILS_HEADERS)
CPARSE_INCLUDES := $(PKGINCDIR) $(CUTILS_INCLUDES)

CPARSE_SRC := $(PKGSRCDIR)
CPARSE_H := $(PKGSRC_H)
CPARSE_INTDIR := $(INTSRCDIR)
CPARSE_OBJ := $(PKGSRC_OBJ)
CPARSE_GCDA := $(PKGSRC_GCDA)
CPARSE := $(PKGLIB)

.PHONY: cparse
cparse: $(CPARSE)

$(CPARSE): $(CPARSE_OBJ)
	@mkdir -p $(@D)
	ar rcs $@ $(CPARSE_OBJ)

$(CPARSE_INTDIR)%.o: $(CPARSE_SRC)%.c $(CPARSE_H) $(CPARSE_HEADERS)
	@mkdir -p $(@D)
	$(TCC) -m$(BITS) -c $(patsubst %,-I%,$(CPARSE_SRC) $(CPARSE_INCLUDES)) $(CFLAGS) -o $@ $<

CPARSE_TEST_LIBS := $(CPARSE) $(CUTILS) $(CTEST) $(CBASE)

CPARSE_TEST_SRC := $(PKGTESTDIR)
CPARSE_TEST_H := $(PKGTEST_H)
CPARSE_TEST_INTDIR := $(INTTESTDIR)
CPARSE_TEST_OBJ := $(PKGTEST_OBJ)
CPARSE_TEST_GCDA := $(PKGTEST_GCDA)
CPARSE_TEST := $(PKGTEST)

.PHONY: cparse_test
cparse_test: $(CPARSE_TEST)
	@rm -rf $(CPARSE_GCDA) $(CPARSE_TEST_GCDA)
	@$(CPARSE_TEST)

$(CPARSE_TEST): $(CPARSE_TEST_OBJ) $(CPARSE_TEST_LIBS)
	@mkdir -p $(@D)
	@$(TCC) -m$(BITS) $(LDFLAGS) -o $@ $(CPARSE_TEST_OBJ) -L$(LIBSDIR) $(patsubst %,-l:%,$(notdir $(CPARSE_TEST_LIBS)))

$(CPARSE_TEST_INTDIR)%.o: $(CPARSE_TEST_SRC)%.c $(CPARSE_TEST_H)  $(CPARSE_HEADERS) $(CTEST_HEADERS)
	@mkdir -p $(@D)
	@$(TCC) -m$(BITS) -c $(patsubst %,-I%,$(CPARSE_TEST_SRC) $(CPARSE_SRC) $(CPARSE_INCLUDES) $(CTEST_INCLUDES)) $(CFLAGS) -o $@ $<
